language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
script:
- npm test
- node lib/run.js --projectKey p --clientId c --clientSecret s --csv data/minimum-header.csv
notifications:
  hipchat:
    rooms:
      secure: TODO
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a><a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
